
# Matrike in operacije
<br/>

<img src="img/img1.jpg"/>


In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

Matrike so <i>urejena polja števil</i>, ki spominja na tabelo. V računalništvu so splošno uporabne, nas pa bo zanimala predvsem uporaba za shranjevanje številskih podatkov. 

In [2]:
A = np.array([[3,4],[4,3], [2, 1]])
A

array([[3, 4],
       [4, 3],
       [2, 1]])

Matrika $\textbf{A}$ je velikosti $3\times2$. Tu je še ena matrika drugačne velikosti:

In [5]:
B = np.array([[1,4.1,3,4],[1,3,2,4],])
B

array([[ 1. ,  4.1,  3. ,  4. ],
       [ 1. ,  3. ,  2. ,  4. ]])

Oglejmo si matriko podatkov ocen filmov, ki ste jo zgradili z odgovori vprašalnik. 

In [6]:
X = np.loadtxt(open("data/vprasalnik.txt", encoding="utf-8"), skiprows=1, delimiter=",")
X

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 5.,  4.,  0., ...,  4.,  5.,  5.],
       [ 1.,  5.,  3., ...,  5.,  0.,  2.],
       [ 0.,  5.,  1., ...,  5.,  0.,  0.]])

$\textbf{X}$ je velika matrika. Ogljemo si nekaj njenih lastnosti ...

In [7]:
# ...
X.shape

(138, 10)

oz. jo narišimo.

In [27]:
import csv
plt.figure()
plt.pcolor(X)
plt.colorbar()
plt.xlabel("Filmi")
plt.ylabel("Uporabniki")
plt.show()

Preberimo še naslove filmov, ki predstavljajo stolpce matrike.

In [11]:
naslovi = csv.DictReader(open("data/vprasalnik.txt"), delimiter=",").fieldnames
naslovi

['Amelie (2001)',
 'Izvor (Inception,  2010)',
 'Vitez teme (The Dark Knight, 2008)',
 'Titanic (1997)',
 'Beležnica (Notebook, 2004)',
 '3 idioti (3 Idiots, 2009)',
 'Matrica (Matrix, 1999)',
 "Življenje je lepo (La vita e' bella, 1997)",
 'Veliki Lebowski (Big Lebowski, 1998)',
 'Reševanje vojaka Ryana (Saving private Ryan, 1998)']

<br/>
<br/>
Matrike so uporabne za učinkovito računanje, saj isto operacijo izvedemo na več številih (poadtkih) hkrati.
Vse operacije, ki jih poznamo na številih, so definiranje tudi na matrikah, npr.
* seštevanje
* odštevanje
* potenciranje
* <b>množenje</B>
* ...



In [17]:
# ...
print(A)
A * A

[[3 4]
 [4 3]
 [2 1]]


array([[ 9, 16],
       [16,  9],
       [ 4,  1]])

Zares uporabna operacija je množenje. Oglejmo si množenje matrik na primeru na tabli!

In [ ]:
# ...


## Matrike nižjega ranga vsebujejo vzorce

Matrika, ki je produkt dveh manjših matrik ima posebne lastnosti. V linearni algebri jim pravimo <i>matrike nižjega ranga</i>. Ali opaziš razliko med matrikama $\textbf{Y}$ in $\textbf{Z}$?

In [25]:
# Y in Z 
Y = np.random.rand(50, 50)
Z = np.random.rand(50, 1).dot(np.random.rand(1, 50))


print("\nY", Y)
print("\nZ", Z)


Y [[ 0.87   0.355  0.931 ...,  0.723  0.405  0.842]
 [ 0.966  0.913  0.818 ...,  0.032  0.209  0.329]
 [ 0.418  0.814  0.471 ...,  0.569  0.332  0.595]
 ..., 
 [ 0.503  0.611  0.493 ...,  0.14   0.947  0.451]
 [ 0.14   0.207  0.67  ...,  0.42   0.751  0.639]
 [ 0.806  0.049  0.109 ...,  0.872  0.796  0.25 ]]

Z [[ 0.349  0.565  0.094 ...,  0.062  0.331  0.087]
 [ 0.386  0.624  0.104 ...,  0.068  0.366  0.096]
 [ 0.524  0.848  0.142 ...,  0.093  0.497  0.131]
 ..., 
 [ 0.076  0.122  0.02  ...,  0.013  0.072  0.019]
 [ 0.48   0.776  0.13  ...,  0.085  0.455  0.12 ]
 [ 0.119  0.193  0.032 ...,  0.021  0.113  0.03 ]]


In [26]:
plt.figure()
fig, axes = plt.subplots(ncols=2, nrows=1, figsize=(15, 7))
axes[1].pcolor(Z)
axes[1].set_title("Z (Matrika nižjega ranga)")
axes[0].pcolor(Y)
axes[0].set_title("Y (Matrika polnega ranga)")
plt.show()

Lastnost matrike, nižjega ranga, ki jo opazimo, s pridom izkoriščajo algoritmi za iskanje vzorcev v 
* priporočilnih sistemih, 
* socialnih omrežjih, 
* slikah, 
* signalih,
* ...

Eden enostavnejših modelov za podatke je <b>faktorski model</b>, pripadajoči algoritem za učenje pa <b>matrična faktorizacija</b>.